/**
 * Demo mode mock data for CourtIQ.
 * Matches the actual Supabase schema so the app renders correctly without credentials.
 */

function daysAgo(n) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
}

function daysAgoISO(n) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const DEMO_PROFILE = {
  id: 'demo-user-id',
  email: 'demo@courtiq.app',
  full_name: 'Chris Marvel',
  position: 'SG',
  skill_level: 'Intermediate',
  onboarding_completed: true,
  xp: 2450,
  level: 8,
  current_streak: 12,
  longest_streak: 21,
  last_activity_date: daysAgo(0),
  avatar_url: null,
  notification_streak_reminders: true,
  notification_weekly_summary: true,
};

// Matches games table: game_date, game_type, result (Win/Loss/Draw), minutes_played, etc.
export const DEMO_GAMES = [
  {
    id: 'demo-game-1',
    user_id: 'demo-user-id',
    game_date: daysAgo(1),
    opponent: 'Westside Ballers',
    location: 'Lincoln Park Gym',
    game_type: 'League',
    result: 'Win',
    minutes_played: 34,
    points: 24,
    rebounds: 6,
    assists: 5,
    steals: 3,
    blocks: 0,
    turnovers: 2,
    fouls: 2,
    fg_made: 9,
    fg_attempted: 17,
    three_made: 4,
    three_attempted: 8,
    ft_made: 2,
    ft_attempted: 2,
    energy_level: 8,
    performance_rating: 9,
    notes: 'Felt great from three. Controlled tempo in the second half.',
    created_at: daysAgoISO(1),
    updated_at: daysAgoISO(1),
  },
  {
    id: 'demo-game-2',
    user_id: 'demo-user-id',
    game_date: daysAgo(4),
    opponent: 'Downtown Runners',
    location: 'YMCA Court 1',
    game_type: 'League',
    result: 'Loss',
    minutes_played: 30,
    points: 14,
    rebounds: 3,
    assists: 7,
    steals: 1,
    blocks: 0,
    turnovers: 5,
    fouls: 3,
    fg_made: 5,
    fg_attempted: 14,
    three_made: 2,
    three_attempted: 7,
    ft_made: 2,
    ft_attempted: 4,
    energy_level: 5,
    performance_rating: 4,
    notes: 'Too many turnovers. Need to tighten handle under pressure.',
    created_at: daysAgoISO(4),
    updated_at: daysAgoISO(4),
  },
  {
    id: 'demo-game-3',
    user_id: 'demo-user-id',
    game_date: daysAgo(7),
    opponent: 'Northside Kings',
    location: 'Memorial Rec Center',
    game_type: 'Tournament',
    result: 'Win',
    minutes_played: 38,
    points: 28,
    rebounds: 5,
    assists: 3,
    steals: 2,
    blocks: 1,
    turnovers: 3,
    fouls: 4,
    fg_made: 11,
    fg_attempted: 20,
    three_made: 3,
    three_attempted: 6,
    ft_made: 3,
    ft_attempted: 4,
    energy_level: 9,
    performance_rating: 8,
    notes: 'Aggressive in the paint. Drew lots of fouls.',
    created_at: daysAgoISO(7),
    updated_at: daysAgoISO(7),
  },
  {
    id: 'demo-game-4',
    user_id: 'demo-user-id',
    game_date: daysAgo(10),
    opponent: 'East Bay Hoopers',
    location: 'Lincoln Park Gym',
    game_type: 'League',
    result: 'Win',
    minutes_played: 32,
    points: 18,
    rebounds: 8,
    assists: 4,
    steals: 1,
    blocks: 0,
    turnovers: 2,
    fouls: 1,
    fg_made: 7,
    fg_attempted: 15,
    three_made: 2,
    three_attempted: 5,
    ft_made: 2,
    ft_attempted: 2,
    energy_level: 7,
    performance_rating: 7,
    notes: 'Crashed the boards hard tonight. Kept us alive in Q4.',
    created_at: daysAgoISO(10),
    updated_at: daysAgoISO(10),
  },
  {
    id: 'demo-game-5',
    user_id: 'demo-user-id',
    game_date: daysAgo(14),
    opponent: 'South City Elite',
    location: 'YMCA Court 2',
    game_type: 'Pickup',
    result: 'Loss',
    minutes_played: 28,
    points: 10,
    rebounds: 2,
    assists: 6,
    steals: 0,
    blocks: 0,
    turnovers: 4,
    fouls: 2,
    fg_made: 4,
    fg_attempted: 13,
    three_made: 1,
    three_attempted: 6,
    ft_made: 1,
    ft_attempted: 2,
    energy_level: 4,
    performance_rating: 3,
    notes: 'Off night shooting. Couldn\'t find rhythm early.',
    created_at: daysAgoISO(14),
    updated_at: daysAgoISO(14),
  },
];

// Matches shot_logs table: session_date, zone_id, shot_type, made, context
const ZONE_IDS = [
  'paint', 'paint', 'paint',
  'left_elbow', 'right_elbow',
  'mid_left', 'mid_right',
  'left_wing_3', 'right_wing_3', 'top_key_3',
  'left_corner_3', 'right_corner_3',
  'free_throw',
];

const SHOT_TYPES = [
  'Catch & Shoot', 'Off Dribble', 'Post Up', 'Free Throw', 'Floater', 'Hook Shot',
];

export const DEMO_SHOT_LOGS = Array.from({ length: 30 }, (_, i) => {
  const zone_id = ZONE_IDS[i % ZONE_IDS.length];
  const isFT = zone_id === 'free_throw';
  const shot_type = isFT ? 'Free Throw' : SHOT_TYPES[i % 3]; // Catch & Shoot, Off Dribble, Post Up
  const made = (i * 7 + 3) % 10 < 6; // ~60% make rate
  return {
    id: `demo-shot-${i + 1}`,
    user_id: 'demo-user-id',
    session_date: daysAgo(Math.floor(i / 6)),
    zone_id,
    shot_type,
    made,
    context: i % 5 === 0 ? 'Game' : 'Practice',
    notes: null,
    created_at: daysAgoISO(Math.floor(i / 6)),
  };
});

// Matches drill_sessions: session_date, category, drill_name, sets, reps, duration_minutes, rating, intensity
export const DEMO_DRILL_SESSIONS = [
  {
    id: 'demo-drill-1',
    user_id: 'demo-user-id',
    session_date: daysAgo(0),
    category: 'Shooting',
    drill_name: 'Spot-Up Threes',
    sets: 5,
    reps: 20,
    duration_minutes: 25,
    rating: 4,
    intensity: 'Medium',
    notes: 'Focused on follow-through.',
    is_custom_drill: false,
    created_at: daysAgoISO(0),
    updated_at: daysAgoISO(0),
  },
  {
    id: 'demo-drill-2',
    user_id: 'demo-user-id',
    session_date: daysAgo(1),
    category: 'Ball Handling',
    drill_name: 'Cone Crossovers',
    sets: 4,
    reps: 12,
    duration_minutes: 15,
    rating: 3,
    intensity: 'High',
    notes: 'Left hand is getting tighter.',
    is_custom_drill: false,
    created_at: daysAgoISO(1),
    updated_at: daysAgoISO(1),
  },
  {
    id: 'demo-drill-3',
    user_id: 'demo-user-id',
    session_date: daysAgo(2),
    category: 'Shooting',
    drill_name: 'Free Throw Routine',
    sets: 5,
    reps: 10,
    duration_minutes: 10,
    rating: 5,
    intensity: 'Low',
    notes: 'Routine is feeling natural.',
    is_custom_drill: false,
    created_at: daysAgoISO(2),
    updated_at: daysAgoISO(2),
  },
  {
    id: 'demo-drill-4',
    user_id: 'demo-user-id',
    session_date: daysAgo(3),
    category: 'Defense',
    drill_name: 'Closeout Slides',
    sets: 3,
    reps: 10,
    duration_minutes: 20,
    rating: 4,
    intensity: 'High',
    notes: 'Worked on staying low.',
    is_custom_drill: false,
    created_at: daysAgoISO(3),
    updated_at: daysAgoISO(3),
  },
  {
    id: 'demo-drill-5',
    user_id: 'demo-user-id',
    session_date: daysAgo(5),
    category: 'Shooting',
    drill_name: 'Pull-Up Mid-Range',
    sets: 4,
    reps: 15,
    duration_minutes: 20,
    rating: 3,
    intensity: 'Medium',
    notes: 'Off the dribble, both directions.',
    is_custom_drill: false,
    created_at: daysAgoISO(5),
    updated_at: daysAgoISO(5),
  },
  {
    id: 'demo-drill-6',
    user_id: 'demo-user-id',
    session_date: daysAgo(6),
    category: 'Conditioning',
    drill_name: 'Court Sprints',
    sets: 4,
    reps: 5,
    duration_minutes: 12,
    rating: 4,
    intensity: 'High',
    notes: 'Pushed for under 4s each.',
    is_custom_drill: false,
    created_at: daysAgoISO(6),
    updated_at: daysAgoISO(6),
  },
  {
    id: 'demo-drill-7',
    user_id: 'demo-user-id',
    session_date: daysAgo(8),
    category: 'Ball Handling',
    drill_name: 'Full Court Dribble Series',
    sets: 3,
    reps: 12,
    duration_minutes: 18,
    rating: 3,
    intensity: 'Medium',
    notes: 'Behind-the-back still needs work.',
    is_custom_drill: false,
    created_at: daysAgoISO(8),
    updated_at: daysAgoISO(8),
  },
  {
    id: 'demo-drill-8',
    user_id: 'demo-user-id',
    session_date: daysAgo(9),
    category: 'Shooting',
    drill_name: 'Catch and Shoot',
    sets: 4,
    reps: 20,
    duration_minutes: 22,
    rating: 5,
    intensity: 'Medium',
    notes: 'Quick release, five spots.',
    is_custom_drill: false,
    created_at: daysAgoISO(9),
    updated_at: daysAgoISO(9),
  },
];

// Matches journal_entries: entry_date, mood (Great/Good/Okay/Bad/Terrible), energy_level,
// sleep_hours, sleep_quality, confidence, focus, motivation, stress, highlights, improvements, etc.
export const DEMO_JOURNAL_ENTRIES = [
  {
    id: 'demo-journal-1',
    user_id: 'demo-user-id',
    entry_date: daysAgo(0),
    mood: 'Great',
    energy_level: 8,
    sleep_hours: 8.5,
    sleep_quality: 9,
    confidence: 9,
    focus: 8,
    motivation: 9,
    stress: 3,
    highlights: 'Visualized my shots before the drill session and everything felt automatic.',
    improvements: 'Need to work on left-hand finishing.',
    goals_for_tomorrow: 'Hit 50 free throws before practice.',
    gratitude: 'Grateful for a healthy body and a team that pushes me.',
    notes: 'Carry this mindset into game day.',
    created_at: daysAgoISO(0),
    updated_at: daysAgoISO(0),
  },
  {
    id: 'demo-journal-2',
    user_id: 'demo-user-id',
    entry_date: daysAgo(3),
    mood: 'Bad',
    energy_level: 5,
    sleep_hours: 6.0,
    sleep_quality: 4,
    confidence: 4,
    focus: 5,
    motivation: 6,
    stress: 7,
    highlights: 'Good assists — finding teammates even when my shot was off.',
    improvements: 'Shot selection. Stop forcing contested threes.',
    goals_for_tomorrow: 'Watch film and focus on ball-handling drills.',
    gratitude: 'Coach gave good feedback after the game.',
    notes: 'Rough practice. Need to bounce back mentally.',
    created_at: daysAgoISO(3),
    updated_at: daysAgoISO(3),
  },
  {
    id: 'demo-journal-3',
    user_id: 'demo-user-id',
    entry_date: daysAgo(6),
    mood: 'Great',
    energy_level: 9,
    sleep_hours: 9.0,
    sleep_quality: 9,
    confidence: 8,
    focus: 9,
    motivation: 10,
    stress: 2,
    highlights: 'Freshest player in the 4th quarter. Conditioning is paying off.',
    improvements: 'Defensive rotations were a step slow in the third.',
    goals_for_tomorrow: 'Study film on pick-and-roll defense.',
    gratitude: 'Great win with the squad. Everyone brought energy.',
    notes: 'Staying disciplined with sleep and nutrition.',
    created_at: daysAgoISO(6),
    updated_at: daysAgoISO(6),
  },
  {
    id: 'demo-journal-4',
    user_id: 'demo-user-id',
    entry_date: daysAgo(10),
    mood: 'Good',
    energy_level: 7,
    sleep_hours: 7.5,
    sleep_quality: 7,
    confidence: 7,
    focus: 7,
    motivation: 8,
    stress: 4,
    highlights: 'Set new monthly goals — FT% to 85%, turnovers under 2 per game.',
    improvements: 'Be more vocal on defense.',
    goals_for_tomorrow: 'Ball-handling session and 100 free throws.',
    gratitude: 'Thankful for the opportunity to compete.',
    notes: 'Time to grind.',
    created_at: daysAgoISO(10),
    updated_at: daysAgoISO(10),
  },
];

// Matches weekly_challenges: title, description, target_value, current_value, challenge_type,
// week_start, completed, xp_reward
export const DEMO_CHALLENGES = [
  {
    id: 'demo-challenge-1',
    user_id: 'demo-user-id',
    title: '100 Free Throws',
    description: 'Make 100 free throws this week.',
    target_value: 100,
    current_value: 100,
    challenge_type: 'shooting',
    week_start: daysAgo(10),
    completed: true,
    xp_reward: 75,
    created_at: daysAgoISO(10),
  },
  {
    id: 'demo-challenge-2',
    user_id: 'demo-user-id',
    title: '5 Drill Sessions',
    description: 'Complete 5 drill sessions this week.',
    target_value: 5,
    current_value: 3,
    challenge_type: 'training',
    week_start: daysAgo(4),
    completed: false,
    xp_reward: 50,
    created_at: daysAgoISO(4),
  },
  {
    id: 'demo-challenge-3',
    user_id: 'demo-user-id',
    title: '50% from Three',
    description: 'Shoot 50%+ from three in your next game.',
    target_value: 1,
    current_value: 0,
    challenge_type: 'shooting',
    week_start: daysAgo(2),
    completed: false,
    xp_reward: 100,
    created_at: daysAgoISO(2),
  },
];

// Matches user_badges joined with badges: badges.name, badges.description, badges.icon, earned_at
export const DEMO_BADGES = [
  {
    id: 'demo-ub-1',
    user_id: 'demo-user-id',
    badge_id: 'demo-badge-1',
    earned_at: daysAgoISO(30),
    badges: { id: 'demo-badge-1', name: 'First Game', description: 'Log your first game.', icon: '🏆', condition_type: 'games_played', condition_value: 1 },
  },
  {
    id: 'demo-ub-2',
    user_id: 'demo-user-id',
    badge_id: 'demo-badge-2',
    earned_at: daysAgoISO(18),
    badges: { id: 'demo-badge-2', name: '7-Day Streak', description: 'Maintain a 7-day activity streak.', icon: '🔥', condition_type: 'streak', condition_value: 7 },
  },
  {
    id: 'demo-ub-3',
    user_id: 'demo-user-id',
    badge_id: 'demo-badge-3',
    earned_at: daysAgoISO(7),
    badges: { id: 'demo-badge-3', name: 'Sharpshooter', description: 'Shoot 60%+ from the field in a game.', icon: '🎯', condition_type: 'fg_pct', condition_value: 60 },
  },
  {
    id: 'demo-ub-4',
    user_id: 'demo-user-id',
    badge_id: 'demo-badge-4',
    earned_at: daysAgoISO(5),
    badges: { id: 'demo-badge-4', name: 'Iron Will', description: 'Complete 10 drill sessions.', icon: '🛡️', condition_type: 'drills_completed', condition_value: 10 },
  },
];

// Pre-computed stats matching getDashboardStats return shape
export const DEMO_DASHBOARD_STATS = {
  gamesPlayed: DEMO_GAMES.length,
  wins: DEMO_GAMES.filter((g) => g.result === 'Win').length,
  losses: DEMO_GAMES.filter((g) => g.result === 'Loss').length,
  winPct: Math.round(
    (DEMO_GAMES.filter((g) => g.result === 'Win').length / DEMO_GAMES.length) * 100
  ),
  avgPoints: Math.round(
    DEMO_GAMES.reduce((s, g) => s + g.points, 0) / DEMO_GAMES.length
  ),
  totalDrills: DEMO_DRILL_SESSIONS.length,
  totalDrillMinutes: DEMO_DRILL_SESSIONS.reduce((s, d) => s + (d.duration_minutes || 0), 0),
  totalShots: DEMO_SHOT_LOGS.length,
  madeShots: DEMO_SHOT_LOGS.filter((s) => s.made).length,
  shootingPct: Math.round(
    (DEMO_SHOT_LOGS.filter((s) => s.made).length / DEMO_SHOT_LOGS.length) * 100
  ),
  journalEntries: DEMO_JOURNAL_ENTRIES.length,
};
